apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - edge_deployment.yaml
  - edge_service.yaml
  - edge_ingress.yaml

#génération d'une configmap managé par Kustomize à partir d'application.yaml
configMapGenerator:
  - name: edge-config #base du nom de la CM générée
    files:
      - application.yaml
    options:
      labels:
        app: edge-service